### ISSUE TITLE
Resolving licensing issues for Debian packaging

### ISSUE THREAD

**Issue by jgru** [simsong/bulk_extractor#168]
Dear Simson, 

I intend to package `bulk_extractor` as a Debian package. Since Debian is strict regarding its licensing terms I have two concerns for you: 

1. GPLv3 and OpenSSL license interoperability
The GPL (including version 3) is incompatible with some terms of the OpenSSL license, and therefore Debian does not allow GPL-licensed code linked with OpenSSL libraries unless there is a license exception explicitly permitting this. Is it possible that you explicitly allow the linkage with OpenSSL libraries by stating an exception in the licensing terms? 

2. License problem with `src/scan_json.cpp`
The MIT license with the additional infamous clause "The Software shall be used for Good, not Evil" is considered to be non-free by various open source projects. This clause is contained within `src/scan_json.cpp`. So the questions is, which part of the before mentioned source file is derived from the JSON-project directly and do you see any possibility to resolve this, e.g. by reimplementing the specific part? 

Since bulk_extractor would be a great addition to Debian's pacakge archives, I would like to hear from you in this regard. 
If I can help somehow to tackle this issues, please let me know.

Best regards
    Jan
 
P.S.: Thanks for providing the software `bulk_extractor` and DFXML!

**Comment by simsong** [comment]
Hi Jan,

Thanks for your email. I'm in the middle of a massive rewrite of bulk_extractor, as you may be aware. 

To answer your questions:

1. I am happy to explicitly permit linking with OpenSSL. For bulk_extractor 2.0, the system will link with either OpenSSL or with Apple's CommonCrypto libraries. If there is a third library to support, please let me know. All of the library support is confined to the DFXML module, so it's easy to change there.

2. I wasn't aware that `"The Software shall be used for Good, not Evil"` was considered an enforceable license term. Presumably it would prevent the use of the software by Lucifer, but by anyone else? What a strange problem we seem to have here.

The JSON checker is from here:
* https://github.com/marcomorain/JSON_checker/blob/master/JSON_checker.c

It is a particularly nice JSON checker.

Hm:
* https://www.synopsys.com/blogs/software-security/json-license-limitations/
* https://tanguy.ortolo.eu/blog/article46/json-license

Alas, I see three options here:

1. Enjoy the JSON license and don't let it get you down.
2. Find me an alternative JSON validator. I'm happy to evaluate any that you think is worthy.
3. Write a new JSON validator.

How would you like to proceed?

**Comment by jgru** [comment]
Hi Simson, 

thank you for the fast reply! 
1. Regarding OpenSSL:
Great! I will prepare a PR, which adds this clause to `LICENSE.md` and documents the permission of linkage with OpenSSL libraries explicitly within the source tree. 

2.  Regarding the JSON-issue:
As the DFSG (Debian Free Software Guidelines) are very strict in this regard, I can't ignore it, as I would probably do it in a personal project. 

After a quick look at the code of `src/scan_json.cpp` it looks like you're only checking for the syntactical correctness. In order to accomplish this in a DFSG-compliant way, I would like to propose the usage of the libary [json-c](https://github.com/json-c/json-c), which is unproblematic in this regard and easy to use. (I have been using it by myself and am quite satisfied with it for my purposes.) It provides an implicit syntax check by calling the function `json_tokener_parse(const char *str)` and returns NULL, if parsing fails. (See https://stackoverflow.com/a/37773385) 
There might be alternative options like the header-only library [jsmn](https://github.com/zserge/jsmn), which provides the function `jsmn_parse(...)`  and returns `JSMN_ERROR_INVAL` on a parsing error.  

Do you think, that one of those libraries could be a viable option? If so, I would offer my help for the modification of `src/scan_json.cpp`. If you don't think so or have a better idea of resolving this, I would be glad to hear from you.

Thanks already in advance! 

Best regards
    Jan

**Comment by simsong** [comment]
json-c looks like it will work. Then Lucifer will be able to use bulk_extractor. The Dark Lord will be pleased.

however, I am hesitant to do the work of incorporating in both 2.0 and in 1.5. It should be easy to make the change. Do you want to give it a try?

**Comment by jgru** [comment]
> json-c looks like it will work. Then Lucifer will be able to use bulk_extractor. The Dark Lord will be pleased.

Haha, the forensics community, which could then "apt-get" bulk_extractor will be pleased even  more probably probably. :smile: :+1: 

> however, I am hesitant to do the work of incorporating in both 2.0 and in 1.5. It should be easy to make the change. Do you want to give it a try?

Sure, I will try it and get back to you. 
Thanks for your openness and help.

**Comment by simsong** [comment]
I'm looking forward to sending out a Tweet along the lines of _`bulk_extractor` can now be used for evil._

**Comment by simsong** [comment]
@jgru — Why is your code not compiling here?
https://github.com/simsong/bulk_extractor/runs/2910172008?check_suite_focus=true

**Comment by jgru** [comment]
> @jgru — Why is your code not compiling here?
> https://github.com/simsong/bulk_extractor/runs/2910172008?check_suite_focus=true

Yes, Ubuntu 20.04 does provide libjson-c-dev in version 0.13, wich does not provide the method 
`end = json_tokener_get_parse_end(jt);`, one must use `end = jt->char_offset;`, which will be remove in future releases, but works still under 0.15. So I prepared a PR for that. See #171, which should fix that. 

Sorry, for not checking that (tested only on Debian Bullseye and Debian is normally behind Ubuntu package sources)!

HTH, @simsong !

Best regards
   Jan

**Comment by simsong** [comment]
Thanks so much! That’s why I deployed GitHub actions!

**Comment by jgru** [comment]
> Thanks so much! That’s why I deployed GitHub actions!

You're welcome, I was happy to do that. 
The issue can be considered to be resolved, I think.

FYI, since those licensing issues are out of the way, I filed an 'Intent to package'-messsage to the Debian bug tracking system this morning, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990302

**Comment by simsong** [comment]
Looks like it is still not compiling?

https://github.com/simsong/bulk_extractor/runs/2912238640?check_suite_focus=true

**Comment by simsong** [comment]
Thanks again for all of your help, @jgru.

**Comment by jgru** [comment]
> Thanks again for all of your help, @jgru.

You're welcome, very happy, that I could help and contribute.

**Comment by simsong** [comment]
Again, I'm super-appreciative for your help. I've been working on the `bulk_extractor` 2.0 rewrite for more than two years now. It's slowly moving along. It has extensive unit tests. It will be much faster. If you have interest, it will be great to have your help once the framework is a little more stable. Right now I'm rewriting the pdf text extractor.

**Comment by jgru** [comment]
Sounds great! I would be glad to contribute to the project -- especially, if it the task has a research-component going beyond software-engineering. So if there is something, that you can/want to delegate for the 2.0 release, please drop me a message (if you prefer,  by mail (address can be found in the linked ITP-bug in the Debians BTS)).

**Comment by simsong** [comment]
Indeed, there is a lot of research to do. Both forensics and high performance  C++ processing design . And using GPUs or vectorized instructions. Take a look at the open issues and the slg-dev branch.

**Comment by jgru** [comment]
> Indeed, there is a lot of research to do. Both forensics and high performance C++ processing design . And using GPUs or vectorized instructions. Take a look at the open issues and the slg-dev branch.

Alright, I'll take a look at https://github.com/simsong/bulk_extractor/blob/slg-dev/TODO.md
And think about contributions, when time permits, but Debian packaging will be the first task I'll work on.

**Comment by simsong** [comment]
Packaging before all of the scanners are operational?

**Comment by jgru** [comment]
> Packaging before all of the scanners are operational?

Since BE is in a stable version and very well usable, we could propose version  1.6.0 for the package archives. Nevertheless, we could wait with that until 2.0. What do you think?

**Comment by simsong** [comment]
So there are issues:
* v1.6.0 compiles on Linux, but not the current version of MacOS, because of Apple deprecating OpenSSL. (It doesn't work easily when OpenSSL is installed via brew)
* The new hash_t type in dfxml works on both, and the current dfxml *might* work with the legacy be13_api, but then again, it might not.
* v2.0 is a complete rewrite and it won't be at full functionality for months at the current rate.
So you can use v1.6.0 for the Linux package archives, and I think that's fine. I would avoid waiting for 2.0, because it might be a long wait.

**Comment by jgru** [comment]
> So there are issues:
> * The new hash_t type in dfxml works on both, and the current dfxml _might_ work with the legacy be13_api, but then again, it might not.

Hi Simson, 

could you elaborate on this? I would want to avoid to package dfxml in an old version, since I use it for other tasks, also. In which situations will the compatibility issues appear?

Best regards  
    Jan

**Comment by simsong** [comment]
I just pushed a new release last night of bulk_extractor that uses the current header-only dfxml_writer. It is in master HEAD but untagged 


----
Sent from my phone.

On Jul 1, 2021, at 1:18 AM, Jan Gruber ***@***.***> wrote:

﻿
So there are issues:

The new hash_t type in dfxml works on both, and the current dfxml might work with the legacy be13_api, but then again, it might not.
Hi Simson,

could you elaborate on this? I would want to avoid to package dfxml in an old version, since I use it for other tasks, also. In which situations will the compatibility issues appear?

Best regards
Jan
